### ISSUE TITLE
Request: network config information

### ISSUE THREAD

**Issue by casusbelli** [j-griffith/sos-ci#13]
Hi!
I've set up a sos-ci installation on a devstack machine which essentially runs tempest & devstack inside  devstack VMs triggered by sos-ci. While this works nicely i do have issues with dhcp (and more network functionalities) for the inner VMs.
The sos-ci setup brings along example settings for the inner devstack VMs. It would be great to have hints / examples for the devstack nova-network (or neutron) config of the external devstack, the one that sos-ci deploys into.
I volunteer to add a documentation / Readme paragraph on this to sos-ci once i get it working... :-D
Cheers
Silvan

**Comment by casusbelli** [comment]
Answering my own request.
We found a rather nasty but working hack, by adding a tap device with a local ip range to inner VMs and using that as a FLAT_INTERFACE for devstack. Not nice but works in our setup.
I'll close this request if there are better solutions, feel free to reopen & share, please. :)

**Comment by j-griffith** [comment]
Sorry I missed this request, I can add networking info for what i use; which is nova-network and can be either a single private_network or two (one standard/default and another for iSCSI traffic).  It sounds like you're doing something similar, send me a note and let me know if I can help further or if you still want to look at adding some additional docs etc.

Sorry for missing this!!!
