### ISSUE TITLE
Best practice for handling gerrit restarts?

### ISSUE THREAD

**Issue by casusbelli** [j-griffith/sos-ci#14]
Hi!
When Gerrit is restarted my sos-ci fork looses the gerrit event stream (requiring manual restart), do you have another approach for this?
Best
Silvan

**Comment by j-griffith** [comment]
Hi Silvan,
Yes, I put the gerrit connection into a while loop with a try/catch that takes care of the issue.  I've included a gist that shows the modifications I made.  I'll look at pushing an updated version with that and some other changes that I've made later this week.

Let me know if this works out for you.

Thanks,
John

https://gist.github.com/j-griffith/1dcad05371de2c436e17

**Comment by casusbelli** [comment]
Hi John!
Took me some time, just added this to a sandbox ci instance for testing, thanks a lot!
I'll follow up when this has been tested...
Thanks again,
Silvan

**Comment by casusbelli** [comment]
Had a gerrit restart occur today, worked nicely. Thanks again!
